In [3]:
import pandas as pd

from data_processing.nkod_datasets import NKOD
import yaml

with open("config_experiments.yaml", "r") as f:
    config = yaml.safe_load(f)

config = config
dataset_portal = NKOD(config)
df = dataset_portal.super_df
df

2026-01-02 21:01:38 - data_processing.nkod_datasets - INFO - File exists
2026-01-02 21:01:38 - data_processing.nkod_datasets - INFO - File is up to date, loading from disk.
2026-01-02 21:01:44 - data_processing.nkod_datasets - INFO - Number of rows: 31665.
2026-01-02 21:01:44 - data_processing.nkod_datasets - INFO - Dataset info loaded.
2026-01-02 21:01:44 - data_processing.nkod_datasets - WARNING - Extended NKOD dataset file not found.

,datová_sada,název,popis,poskytovatel,periodicita_aktualizace,klíčová_slova,prostorové_pokrytí,téma,právní_předpis
0,https://data.gov.cz/zdroj/datové-sady/70889546...,Investiční pobídky,Datová sada s prostorovou lokalizací investičn...,Královéhradecký kraj,nepravidelný,"[Královéhradecký kraj, Investiční pobídky]",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
2,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Kněžnice,Veřejná stavová data ZPS - podrobné body pro o...,Královéhradecký kraj,roční,"[Královéhradecký kraj, IS DTM, Katalog otevřen...",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
6,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Ostroměř,Veřejná stavová data ZPS - odvozené plošné typ...,Královéhradecký kraj,roční,"[Královéhradecký kraj, IS DTM, Katalog otevřen...",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
10,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Střevač,Veřejná stavová data ZPS - odvozené plošné typ...,Královéhradecký kraj,roční,"[Královéhradecký kraj, IS DTM, Katalog otevřen...",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
14,https://data.gov.cz/zdroj/datové-sady/70889546...,ZPS obec Ledce,Veřejná stavová data ZPS - podrobné body pro o...,Královéhradecký kraj,roční,"[Královéhradecký kraj, IS DTM, Katalog otevřen...",[https://linked.cuzk.cz/resource/ruian/vusc/86],[Hospodářství a finance],[http://data.europa.eu/eli/dir/2019/1024/oj]
...,...,...,...,...,...,...,...,...,...
262278,https://data.gov.cz/zdroj/datové-sady/00304450...,Úřední deska Vsetín,Tato datová sada obsahuje data z úředních dese...,Město Vsetín,denní,[úřední deska],[https://linked.cuzk.cz/resource/ruian/obec/54...,"[úřední dokument, Vláda a veřejný sektor]",[http://data.europa.eu/eli/dir/2019/1024/oj]
262284,https://data.gov.cz/zdroj/datové-sady/00244686...,Úřední deska města Borovany,Datová sada obsahuje dokumenty úřední desky mě...,Město Borovany,denní,[Úřední deska Borovany],[https://linked.cuzk.cz/resource/ruian/obec/54...,"[úřední dokument, Regiony a města, Vláda a veř...",[http://data.europa.eu/eli/dir/2019/1024/oj]
262290,https://data.gov.cz/zdroj/datové-sady/00064467...,Kategorizace,Kategorizace knih v městské knihovně:\r\n\r\n-...,Městská knihovna v Praze,roční,[Praha],[https://linked.cuzk.cz/resource/ruian/kraje/31],[Předběžné údaje],[http://data.europa.eu/eli/dir/2019/1024/oj]
262291,https://data.gov.cz/zdroj/datové-sady/00064467...,Výpůjčky,Výpujčky v městské knihovně dle oboru a pobočk...,Městská knihovna v Praze,čtvrtletní,[Praha],[https://linked.cuzk.cz/resource/ruian/kraje/31],[Předběžné údaje],[http://data.europa.eu/eli/dir/2019/1024/oj]
262292,https://data.gov.cz/zdroj/datové-sady/00241687...,Úřední deska,Tato datová sada obsahuje data z úřední desky ...,Městská část Praha 13,denní,[úřední deska],[https://linked.cuzk.cz/resource/ruian/momc/53...,[Vláda a veřejný sektor],[http://data.europa.eu/eli/dir/2019/1024/oj]

In [4]:
# get all unique themes
themes = df["téma"].explode().unique()
themes

array(['Hospodářství a finance', 'Životní prostředí', 'Zdraví', 'Doprava',
       'Spravedlnost, právní systém a veřejná bezpečnost',
       'Vzdělávání, kultura a sport', 'Předběžné údaje',
       'Regiony a města', 'Vláda a veřejný sektor', 'úřední dokument',
       'Věda a technika', 'Populace a společnost', 'místní médium',
       'novinka', 'Zemědělství, rybolov, lesnictví a výživa',
       'zdravotnická služba', 'zdravotnická technologie', 'hospitalizace',
       'organizace dopravy', 'sociální služby', 'veřejná správa',
       'dopravní prostředek', 'autobus', 'městská doprava',
       'dopravní oblast', 'vodní tok', 'povodeň', 'správní celek',
       '52 ŽIVOTNÍ PROSTŘEDÍ', 'územní management', None,
       'rozpočet kraje', 'rozpočtová politika', 'kontrola rozpočtu',
       'veřejné finance', 'plnění rozpočtu', 'elektronické publikování',
       'nákladní doprava', 'pozemní doprava', 'dopravní přestupek',
       'silniční doprava', 'vozidlo', 'slovník', 'Energie',
       'krátkodobé financování', 'všeobecné zdravotní pojištění',
       'identifikační průkaz', 'cestovní pas', 'územní samospráva',
       'výkonná moc', 'samospráva', 'pravomoc výkonné moci',
       'regionální orgány státní správy', 'výkonný orgán',
       'správa věcí veřejných', 'veřejná služba', 'orgány veřejné správy',
       'místní orgány státní správy', 'pravomoc instituce',
       'místo přechodného pobytu', 'způsobilost k právním úkonům',
       'dělení podle pohlaví', 'otevřená data', 'metadata', 'katalog',
       'katastr nemotivostí', 'rodinný stav', 'regulace telekomunikací',
       'telekomunikační technika', 'mobilní aplikace', 'zpráva',
       'investiční projekt', 'pronájem nemovitosti', 'síť škol',
       'místní zastupitelstvo', 'ročenka', 'státní zdravotní služba',
       'prevence nemocí', 'rakovina', 'kardiovaskulární onemocnění',
       'epidemie', 'epidemiologie', 'zdravotní statistika', 'očkování',
       'léčivý přípravek', 'mateřství', 'onemocnění cest dýchacích',
       'nemoc', 'zdravotní péče', 'plodnost', 'porodnost',
       'mentální choroba', 'převoz nemocných', '2841 zdraví',
       'zpřístupňování informací', 'počítačová gramotnost', 'databáze',
       'zdraví veřejnosti', 'organizace zdravotnictví', 'kožní nemoc',
       'úraz', 'zdravotní systém', 'úmrtnost', 'oplodnění ve zkumavce',
       'výdaje na zdraví', 'zdravotnická legislativa',
       'zdravotní politika', 'infekční nemoc', 'zdravotnické zařízení',
       'vakcína', 'kódování', 'klasifikace', 'statistická nomenklatura',
       'endokrinní nemoc', 'telekomunikační politika',
       'maloobchodní cena', 'zaměstnanci', 'správní rozhodnutí',
       'poštovní služba', 'správní řízení', 'televize',
       'odborná kvalifikace', 'zdravotně postižený pracovník', 'rozpočet',
       'univerzální služba', 'fakturace', 'komunální odpad',
       'obecní rozpočet', 'bydlení', 'organizace', 'plán', 'volný čas',
       'sport', 'cyklistická stezka', 'právní předpisy místní správy',
       'finance místních úřadů', 'místní daň', 'kolejové vozidlo',
       'městská hromadná doprava', 'veřejná doprava', 'podnik služeb',
       'odpad', 'vývoz odpadu', 'parkovací plocha', 'silniční síť',
       'městské komunikace', 'město', 'železniční síť', 'stojatá voda',
       'průmyslový pozemek', 'železniční doprava', 'vlakové nádraží',
       'zelená plocha', 'les', 'nemovitost', 'Moravskoslezský kraj',
       'regionální plánování', 'urbanismus', 'atlas',
       'ochrana rostlinné říše', 'veřejné školství', 'vzdělávání',
       'soukromé školství', 'výchovně vzdělávací zařízení',
       'školní vzdělávání', 'bydlení ve městě', 'soutěž', 'architektura',
       'školní jídelna', 'jednostopé vozidlo', 'kvalita ovzduší',
       'financování z veřejných prostředků', '32 VZDĚLÁVÁNÍ A KOMUNIKACE',
       'geologie', 'důlní provoz', 'výsledek hlasování',
       'poptávka po zaměstnání', 'stupeň vzdělání', 'školství',
       'politika zaměstnanosti EU', 'vytváření pracovních příležitostí',
       'Česko', 'nabídka zaměstnání', 'zaměstnavatel', 'pracovní vztahy',
       'pracovní doba', 'stavba', 'zprostředkovatelna práce',
       'rozdělení podle věku', 'kultura', 'profesní příprava',
       'trh práce', 'popis práce', 'hlídání dětí', 'bezpečnost při práci',
       'mzdová politika', 'pokuta', 'administrativní kontrola',
       'organizace školství', 'organizace výzkumu', 'výzkum',
       'vědecký výzkum', 'institucionální struktura', 'typ podniku',
       'Kypr', 'předmět podnikání', 'umístění podniku',
       '40 PODNIKÁNÍ A HOSPODÁŘSKÁ SOUTĚŽ', 'Lotyšsko', 'Estonsko',
       'mzdové tarify', 'Finsko', 'Rumunsko', 'důchodový plán',
       'výkon rozhodnutí', 'podmínky pro odchod do důchodu',
       'Mezinárodní otázky', 'lékařský posudek', 'zdravotní pojištění',
       'důchodce', 'osoba samostatně výdělečně činná',
       'pracovní nezpůsobilost', 'vyhláška', 'sociální zabezpečení',
       'demografie', 'informační středisko', 'administrativní členění',
       'statistika', 'právo na informace', 'zdravotně postižený člověk',
       'zdravotní průkaz', 'pojišťovna', 'měsíční mzda', 'penále',
       'sportovní událost', 'evropská kulturní událost',
       'obchodní událost', 'nakládání s odpadem', 'zneškodňování odpadu',
       'skladování odpadu', 'organizační schéma', 'rozhodnutí',
       'vztahy mezi institucemi', 'zabavení věci', 'bezolovnatý benzin',
       'motorové palivo', 'zemní plyn', 'benzin', 'plyn',
       'dieselová nafta', 'spalovací plyny', 'palivo',
       'ochrana spotřebitele', 'informace', 'fosilní palivo',
       'mezinárodní politika', 'zákon', 'kontrolní úřad',
       'smlouva na veřejnou zakázku', 'ministerstvo',
       'nevládní organizace', 'dopravní nehoda', 'region',
       'činnost orgánů', 'stavební památky', 'kulturní dědictví',
       'přírodní rezervace ve městě', 'kemp', 'sportovní organizace',
       'knižní průmysl', 'mezinárodní půjčka', 'mateřská škola',
       'kulturní akce', 'mezinárodní vodní cesta',
       'vnitrozemská vodní doprava', 'vnitrozemská vodní cesta',
       'informační systém', 'mezinárodní doprava', 'nerostné zdroje',
       'historie', 'zoologická zahrada'], dtype=object)

In [5]:
keywords = df["klíčová_slova"].explode().unique()
print(keywords)

['Královéhradecký kraj' 'Investiční pobídky' 'IS DTM' ... 'Pohořelice'
 'Město Pohořelice' 'Úřední deska Borovany']

In [12]:
df_metadata = pd.read_csv("../data/datasets_with_metadata.csv")
df_metadata

,title,description,url,keywords,themes,provider,legal_regulations,categories,region,time_period
0,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['oxid uhličitý', 'Národní', 'oxid dusný', 'St...",['Životní prostředí'],Český hydrometeorologický ústav,"['http://data.europa.eu/eli/dir/2019/1024/oj',...",['Životní prostředí'],[],[]
1,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['ČHMÚ', 'Český hydrometeorologický ústav', 't...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],['Životní prostředí'],[],"['1991–2020', 'květen']"
2,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['ČHMÚ', 'Český hydrometeorologický ústav', 'N...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],['Životní prostředí'],[],"['únor', '1991–2020']"
3,Stavební uzávěry,Stavební uzávěry vyplývající z vyhlášek hl. m....,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Urbanismus/Urban planning', 'Urbanismus/Urba...",['Regiony a města'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Doprava']",['Praha'],[]
4,Stanoviště tříděného odpadu,Stanoviště tříděného odpadu. Tato stanoviště m...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Odpady/Waste', 'Odpady/Waste', 'Urbanismus/U...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Životní prostředí']",['Praha'],[]
5,Protipovodňová ochrana,Objekt (zařízení) protipovodňové ochrany zápla...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Technická infrastruktura/Infrastructure', 'Z...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Životní prostředí', 'Regiony a města']","['Praha', 'Vltava', 'Berounka']",[]
6,Protihlukové valy,Protihlukové valy mají charakter sypaného zemn...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Hluk/Noise', 'Hluk/Noise']",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Životní prostředí']",['Praha'],[]
7,Pošty,Bodová vrstva obsahuje data o poštách a ostatn...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Využití území', 'Urbanismus/Urban planning',...",['Hospodářství a finance'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']",['Praha'],[]
8,"PoskytovatelZookoutky Lesů HMP a dále farmy, t...",Veřejně přístupné (v rámci provozní doby areál...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Ochrana přírody/Nature conservation', 'Ochra...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Životní prostředí', 'Regiony a města']",['Praha'],['září 2024']
9,Veřejné zakázky příspěvkových organizací MHMP,Data o zadaných a ukončených veřejných zakázká...,https://data.gov.cz/zdroj/datové-sady/02795281...,"[' ', 'veřejné zakázky', 'veřejné zakázky']","['financování z veřejných prostředků', 'Hospod...","Operátor ICT, a.s.",['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Vláda a veřejný sektor', 'Hospodářství a fin...",['Praha'],[]

,title,description,url,keywords,themes,provider,legal_regulations,categories,region,time_period
0,Aproximativní inventura emisí skleníkových plynů,Dle nařízení Evropského parlamentu a rady EU 2...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['oxid uhličitý', 'Národní', 'oxid dusný', 'St...",['Životní prostředí'],Český hydrometeorologický ústav,"['http://data.europa.eu/eli/dir/2019/1024/oj',...",['Životní prostředí'],[],[]
1,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['ČHMÚ', 'Český hydrometeorologický ústav', 't...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],['Životní prostředí'],[],"['1991–2020', 'květen']"
2,Mapa normálu úhrnu doby trvání slunečního svit...,Mapa normálu úhrnu doby trvání slunečního svit...,https://data.gov.cz/zdroj/datové-sady/00020699...,"['ČHMÚ', 'Český hydrometeorologický ústav', 'N...",['Životní prostředí'],Český hydrometeorologický ústav,['http://data.europa.eu/eli/dir/2019/1024/oj'],['Životní prostředí'],[],"['únor', '1991–2020']"
3,Stavební uzávěry,Stavební uzávěry vyplývající z vyhlášek hl. m....,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Urbanismus/Urban planning', 'Urbanismus/Urba...",['Regiony a města'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Doprava']",['Praha'],[]
4,Stanoviště tříděného odpadu,Stanoviště tříděného odpadu. Tato stanoviště m...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Odpady/Waste', 'Odpady/Waste', 'Urbanismus/U...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Životní prostředí']",['Praha'],[]
5,Protipovodňová ochrana,Objekt (zařízení) protipovodňové ochrany zápla...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Technická infrastruktura/Infrastructure', 'Z...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Životní prostředí', 'Regiony a města']","['Praha', 'Vltava', 'Berounka']",[]
6,Protihlukové valy,Protihlukové valy mají charakter sypaného zemn...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Hluk/Noise', 'Hluk/Noise']",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Životní prostředí']",['Praha'],[]
7,Pošty,Bodová vrstva obsahuje data o poštách a ostatn...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Využití území', 'Urbanismus/Urban planning',...",['Hospodářství a finance'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Regiony a města', 'Hospodářství a finance']",['Praha'],[]
8,"PoskytovatelZookoutky Lesů HMP a dále farmy, t...",Veřejně přístupné (v rámci provozní doby areál...,https://data.gov.cz/zdroj/datové-sady/70883858...,"['Ochrana přírody/Nature conservation', 'Ochra...",['Životní prostředí'],Institut plánování a rozvoje hlavního města Prahy,['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Životní prostředí', 'Regiony a města']",['Praha'],['září 2024']
9,Veřejné zakázky příspěvkových organizací MHMP,Data o zadaných a ukončených veřejných zakázká...,https://data.gov.cz/zdroj/datové-sady/02795281...,"[' ', 'veřejné zakázky', 'veřejné zakázky']","['financování z veřejných prostředků', 'Hospod...","Operátor ICT, a.s.",['http://data.europa.eu/eli/dir/2019/1024/oj'],"['Vláda a veřejný sektor', 'Hospodářství a fin...",['Praha'],[]

In [7]:
categories = df["kategorie_hvd_název"].explode().unique()
print(categories)
# count how many datasets have any category assigned - it is not none

count = df["kategorie_hvd_název"].notna().sum()
print(f"Number of datasets with category assigned: {count}")
# categories = df["kategorie_hvd_IRI"].explode().unique()
# print(categories)

# get df that has category assigned
df_with_category = df[df["kategorie_hvd_název"].notna()]
df_with_category

KeyError: 'kategorie_hvd_název'